### PR TITLE
Added waiting room and create supers code

### PR DESCRIPTION
**Pull request by mathewantony31**
Everything still is in one file. I'll eventually break them down into smaller files

### CODE REVIEW

**Review by philkjacobs — CHANGES_REQUESTED** [review]
The 2nd commit here lgtm.

For the 1st commit, I'm still not comfortable w/ using an unverified CDN.

**Comment by philkjacobs** [comment]
This PR is now obsoleted by the other one landing, right?

**Comment by mathewantony31** [comment]
yeah..

**Comment by mathewantony31** [comment]
Actually this has some new edits that'll need to be merged into master

**Pull request merged**
