### PR TITLE
Improved wait screen style and join game flow 

### PR DESCRIPTION
**Pull request by mathewantony31**
- Joining a game from a link will take you directly to the waiting room after entering your name
- Also added a few formatting improvements to the transitional screens

### CODE REVIEW

**Comment by philkjacobs** [comment]
I already merged this in

**Comment by mathewantony31** [comment]
I added a few more changes after you merged it

**Comment by philkjacobs** [comment]
Ah they werent showing up before until I refreshed.

**Review by philkjacobs — APPROVED** [review]
looks fab

**Pull request merged**
